// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoidsoy4zKv7uxcca5Z1L5EbnxQ4VEho0',
    appId: '1:233660722047:android:ee90072abafd1e244a484a',
    messagingSenderId: '233660722047',
    projectId: 'medifirst-a7aeb',
    storageBucket: 'medifirst-a7aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIlH8IBPMLuIne__pNtAQcTx1cvwZTTo',
    appId: '1:233660722047:ios:83f3c37ca866c9234a484a',
    messagingSenderId: '233660722047',
    projectId: 'medifirst-a7aeb',
    storageBucket: 'medifirst-a7aeb.appspot.com',
    androidClientId: '233660722047-5ibltvo024dabn7g84kfttafheqmm8aa.apps.googleusercontent.com',
    iosClientId: '233660722047-aae8ds9n97ua54hiu7pmbgtv4mrqc17i.apps.googleusercontent.com',
    iosBundleId: 'com.medifirst.medifirst',
  );
}
